name: SST workflow Dev
on: push

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployApp:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          role-to-assume: arn:aws:iam::326850916502:role/GitHub
          aws-region: us-east-1
      - name: Set the node version
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
      - name: Deploy app running sst deploy command
        run: npm i && npx sst deploy --stage prod
